### ISSUE TITLE
Use associative indexes

### ISSUE THREAD

**Issue by fabiocarneiro** [DASPRiD/Dash#60]
Numeric indexes are useful for writing less, but you still need to remember the correct order. Associative indexes allow the values to be placed in any order and are much easier to be overloaded.

**Comment by DASPRiD** [comment]
Associative indexes are supported, see readme.

**Comment by fabiocarneiro** [comment]
@DASPRiD I know they're supported. I meant that IMO I would prefer they to be mandatory.

**Comment by DASPRiD** [comment]
I see absolutely no reason for that. Me and many others prefer a less verbose form of route configuration, especially because so many keys repeat all the time. And since you can override the indexed keys with the associative ones, there's no problem with that. Why would you want to take away a possibility from other people?
